import salesEs from "@/assets/careers-sales-es.pdf.asset.json";
import salesEn from "@/assets/careers-sales-en.pdf.asset.json";
import ehsEs from "@/assets/careers-ehs-es.pdf.asset.json";
import ehsEn from "@/assets/careers-ehs-en.pdf.asset.json";

export const careers = {
  es: {
    tab: "Bolsa de Trabajo", eyebrow: "Trabaja en XD Materials", title: "Las baterías de los autos eléctricos necesitan un destino. Constrúyelo con nosotros.",
    intro: "Cada mes hay más vehículos eléctricos en México y casi nadie está resolviendo qué pasa con sus baterías. En XD Materials lo hacemos, y buscamos a quienes quieran construirlo desde el inicio.",
    principles: ["Impacto ambiental real", "Crecimiento profesional", "Una industria que apenas nace"],
    whyTitle: "Por qué importa", why: "Una batería de ion-litio al final de su vida útil es un residuo que debe manejarse con cuidado, y también una fuente de minerales que pueden volver a usarse. Nuestro trabajo es que llegue al lugar correcto, de forma segura y documentada.",
    whyItems: [["Recolectamos", "baterías de vehículos eléctricos en todo México."], ["Resguardamos", "en nuestra estación de transferencia en Arteaga, Coahuila, con permisos ambientales vigentes."], ["Reciclamos", "las enviamos a reciclaje certificado en Estados Unidos, con trazabilidad documental."]],
    first12: "Tus primeros 12 meses", copy: "Copiar enlace", copied: "Enlace copiado",
    quote: "Empezamos XD Materials porque vimos un problema que nadie estaba resolviendo. Somos un equipo pequeño, y eso significa que tu trabajo se nota desde la primera semana. Si quieres construir algo y no solo ocupar un puesto, queremos conocerte.", quoteName: "Christian Recio", quoteRole: "Director de Operaciones",
    processTitle: "Cómo es el proceso", process: ["Envía tu CV. Te respondemos en un máximo de 5 días hábiles.", "Llamada de 30 minutos para conocernos.", "Entrevista con la Dirección y, para el puesto de EHS, visita a la estación de Arteaga."],
    openTitle: "¿No ves tu puesto?", openText: "Estamos creciendo. Escríbenos, cuéntanos qué harías en XD Materials y adjunta tu CV.", openCta: "Enviar mi CV", openSubject: "Candidatura abierta",
    openings: "Vacantes abiertas", count: "2 oportunidades", start: "Inicio: noviembre 2026", reports: "Reporta al Director de Operaciones",
    responsibilities: "Tu misión", requirements: "Lo que buscamos", offer: "Lo que ofrecemos",
    apply: "Postularme por correo", pdf: "Ver vacante completa (PDF)",
    howTitle: "Tu siguiente paso empieza aquí.", how: "Envía tu CV a crecio@xd-global.com con el asunto de la vacante que te interesa.",
    emailNote: "Adjunta tu CV antes de enviar el correo.", subject: "Asunto",
    roles: [
      { id: "sales", anchor: "ventas", title: "Ejecutivo(a) de Ventas", specialty: "Adquisición de Baterías EV", location: "Monterrey o Saltillo", mode: "Híbrido · Viajes en México", subject: "Ventas Baterías EV", pdf: salesEs.url,
        first12: ["A los 30 días: dominas el servicio, los precios y los permisos, y tienes tu mapa de cuentas objetivo.", "A los 90 días: cierras tus primeras cuentas y entregas tus primeras toneladas.", "A los 12 meses: una cartera de proveedores recurrentes que genera volumen cada mes."],
        mission: "Convierte flotillas, aseguradoras, deshuesaderos y talleres en proveedores recurrentes. Tu resultado se mide en toneladas de baterías adquiridas.",
        responsibilities: ["Prospectar y abrir cuentas nuevas.", "Llevar el ciclo comercial hasta la primera recolección.", "Preparar propuestas y mantener el CRM al día."],
        requirements: ["2+ años en ventas B2B o compras, con nuevas cuentas demostrables.", "Experiencia en prospección en frío: llamadas, visitas y LinkedIn.", "Licencia vigente, disponibilidad para viajar e inglés intermedio."],
        offer: ["Sueldo base + comisiones sin tope por tonelada adquirida.", "Crecimiento hacia cuentas de armadoras y expansión a Centro y Sudamérica.", "Prestaciones de ley."],
      },
      { id: "ehs", anchor: "ehs", title: "Coordinador(a) de EHS", specialty: "Cumplimiento Ambiental", location: "Arteaga, Coahuila", mode: "100% presencial", subject: "EHS Arteaga", pdf: ehsEs.url,
        first12: ["A los 3 meses: tomas control del expediente de permisos, con calendario de vencimientos y obligaciones.", "A los 6 meses: gestionas permisos directamente ante la autoridad estatal y SEMARNAT.", "A los 12 meses: apruebas una auditoría de armadora sin hallazgos mayores y cierras el año sin accidentes incapacitantes."],
        mission: "Lidera el cumplimiento ambiental y la seguridad de la operación. Trae la gestión de permisos a casa y prepara a XD para auditorías de armadoras.",
        responsibilities: ["Gestionar permisos ambientales estatales y federales.", "Liderar procedimientos de seguridad, capacitación y cumplimiento STPS.", "Controlar manifiestos y documentación logística."],
        requirements: ["Ingeniería ambiental, industrial, química o afín; 3+ años en EHS o cumplimiento ambiental.", "Experiencia con SEMARNAT o autoridad estatal, manifiestos y NOM de la STPS.", "Inglés intermedio y residencia en Saltillo o Arteaga."],
        offer: ["Responsabilidad total sobre la función.", "Construye la función y el equipo de EHS conforme crezca la operación.", "Prestaciones de ley."],
      },
    ],
  },
  en: {
    tab: "Careers", eyebrow: "Work at XD Materials", title: "Electric vehicle batteries need somewhere to go. Build it with us.",
    intro: "Mexico adds electric vehicles every month, and almost nobody is solving what happens to their batteries. At XD Materials we do, and we are looking for people who want to build it from the start.",
    principles: ["Real environmental impact", "Career growth", "An industry just getting started"],
    whyTitle: "Why it matters", why: "A lithium-ion battery at end of life is waste that must be handled with care, and also a source of minerals that can be used again. Our job is to get it to the right place, safely and with full documentation.",
    whyItems: [["We collect", "electric vehicle batteries across Mexico."], ["We store", "at our transfer station in Arteaga, Coahuila, under current environmental permits."], ["We recycle", "we ship them to certified recycling in the United States, with documented traceability."]],
    first12: "Your first 12 months", copy: "Copy link", copied: "Link copied",
    quote: "We started XD Materials because we saw a problem nobody was solving. We are a small team, which means your work shows from the first week. If you want to build something and not just fill a position, we want to meet you.", quoteName: "Christian Recio", quoteRole: "Director of Operations",
    processTitle: "How the process works", process: ["Send your CV. We reply within 5 business days.", "A 30-minute call to get to know each other.", "Interview with leadership and, for the EHS role, a visit to the Arteaga station."],
    openTitle: "Don't see your role?", openText: "We are growing. Write to us, tell us what you would do at XD Materials and attach your CV.", openCta: "Send my CV", openSubject: "Open application",
    openings: "Open positions", count: "2 opportunities", start: "Start: November 2026", reports: "Reports to the Director of Operations",
    responsibilities: "Your mission", requirements: "What you bring", offer: "What we offer",
    apply: "Apply by email", pdf: "View full job description (PDF)",
    howTitle: "Your next step starts here.", how: "Send your CV to crecio@xd-global.com with the subject line for your chosen role.",
    emailNote: "Attach your CV before sending your email.", subject: "Subject",
    roles: [
      { id: "sales", anchor: "ventas", title: "Sales Executive", specialty: "EV Battery Acquisition", location: "Monterrey or Saltillo", mode: "Hybrid · Travel within Mexico", subject: "EV Battery Sales", pdf: salesEn.url,
        first12: ["By day 30: you know the service, pricing and permits, and have your target account map.", "By day 90: you close your first accounts and deliver your first tons.", "By month 12: a portfolio of recurring suppliers producing volume every month."],
        mission: "Turn fleets, insurers, salvage yards and repair shops into recurring suppliers. Your results are measured in tons of batteries acquired.",
        responsibilities: ["Prospect and open new accounts.", "Own the sales cycle through the first pickup.", "Prepare proposals and keep the CRM current."],
        requirements: ["2+ years in B2B sales or procurement, with demonstrable new accounts.", "Comfortable with cold prospecting: calls, visits and LinkedIn.", "Valid driver’s license, availability to travel, intermediate English and fluent Spanish."],
        offer: ["Base salary + uncapped commission per ton acquired.", "Growth into automaker accounts and expansion into Central and South America.", "Statutory benefits."],
      },
      { id: "ehs", anchor: "ehs", title: "EHS Coordinator", specialty: "Environmental Compliance", location: "Arteaga, Coahuila", mode: "100% on site", subject: "EHS Arteaga", pdf: ehsEn.url,
        first12: ["By month 3: you take control of the permit file, with a calendar of expirations and obligations.", "By month 6: you handle permits directly with the state authority and SEMARNAT.", "By month 12: you pass an automaker audit with no major findings and close the year with no lost-time accidents."],
        mission: "Lead environmental compliance and the safety of the operation. Bring permitting in-house and get XD ready for automaker audits.",
        responsibilities: ["Manage state and federal environmental permits.", "Lead safety procedures, training and STPS compliance.", "Control waste manifests and logistics documentation."],
        requirements: ["Environmental, industrial, chemical or related engineering degree; 3+ years in EHS or environmental compliance.", "Experience with SEMARNAT or a state authority, waste manifests and STPS standards.", "Intermediate English, fluent Spanish and residence in Saltillo or Arteaga."],
        offer: ["Full ownership of the function.", "Build the EHS function and team as the operation grows.", "Statutory benefits."],
      },
    ],
  },
} as const;