/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CumplimientoRouteImport } from './routes/cumplimiento'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LogisticaRouteImport } from './routes/logistica'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as ProcesoRouteImport } from './routes/proceso'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as MaterialesIndexRouteImport } from './routes/materiales.index'
import { Route as MaterialesSlugRouteImport } from './routes/materiales.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CumplimientoRoute = CumplimientoRouteImport.update({
  id: '/cumplimiento',
  path: '/cumplimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticaRoute = LogisticaRouteImport.update({
  id: '/logistica',
  path: '/logistica',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcesoRoute = ProcesoRouteImport.update({
  id: '/proceso',
  path: '/proceso',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialesIndexRoute = MaterialesIndexRouteImport.update({
  id: '/materiales/',
  path: '/materiales/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialesSlugRoute = MaterialesSlugRouteImport.update({
  id: '/materiales/$slug',
  path: '/materiales/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/cumplimiento': typeof CumplimientoRoute
  '/legal': typeof LegalRoute
  '/logistica': typeof LogisticaRoute
  '/nosotros': typeof NosotrosRoute
  '/proceso': typeof ProcesoRoute
  '/servicios': typeof ServiciosRoute
  '/materiales/$slug': typeof MaterialesSlugRoute
  '/materiales/': typeof MaterialesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/cumplimiento': typeof CumplimientoRoute
  '/legal': typeof LegalRoute
  '/logistica': typeof LogisticaRoute
  '/nosotros': typeof NosotrosRoute
  '/proceso': typeof ProcesoRoute
  '/servicios': typeof ServiciosRoute
  '/materiales/$slug': typeof MaterialesSlugRoute
  '/materiales': typeof MaterialesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/cumplimiento': typeof CumplimientoRoute
  '/legal': typeof LegalRoute
  '/logistica': typeof LogisticaRoute
  '/nosotros': typeof NosotrosRoute
  '/proceso': typeof ProcesoRoute
  '/servicios': typeof ServiciosRoute
  '/materiales/$slug': typeof MaterialesSlugRoute
  '/materiales/': typeof MaterialesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/cumplimiento'
    | '/legal'
    | '/logistica'
    | '/nosotros'
    | '/proceso'
    | '/servicios'
    | '/materiales/$slug'
    | '/materiales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/cumplimiento'
    | '/legal'
    | '/logistica'
    | '/nosotros'
    | '/proceso'
    | '/servicios'
    | '/materiales/$slug'
    | '/materiales'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/cumplimiento'
    | '/legal'
    | '/logistica'
    | '/nosotros'
    | '/proceso'
    | '/servicios'
    | '/materiales/$slug'
    | '/materiales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  CumplimientoRoute: typeof CumplimientoRoute
  LegalRoute: typeof LegalRoute
  LogisticaRoute: typeof LogisticaRoute
  NosotrosRoute: typeof NosotrosRoute
  ProcesoRoute: typeof ProcesoRoute
  ServiciosRoute: typeof ServiciosRoute
  MaterialesSlugRoute: typeof MaterialesSlugRoute
  MaterialesIndexRoute: typeof MaterialesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cumplimiento': {
      id: '/cumplimiento'
      path: '/cumplimiento'
      fullPath: '/cumplimiento'
      preLoaderRoute: typeof CumplimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistica': {
      id: '/logistica'
      path: '/logistica'
      fullPath: '/logistica'
      preLoaderRoute: typeof LogisticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proceso': {
      id: '/proceso'
      path: '/proceso'
      fullPath: '/proceso'
      preLoaderRoute: typeof ProcesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiales/': {
      id: '/materiales/'
      path: '/materiales'
      fullPath: '/materiales/'
      preLoaderRoute: typeof MaterialesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiales/$slug': {
      id: '/materiales/$slug'
      path: '/materiales/$slug'
      fullPath: '/materiales/$slug'
      preLoaderRoute: typeof MaterialesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  CumplimientoRoute: CumplimientoRoute,
  LegalRoute: LegalRoute,
  LogisticaRoute: LogisticaRoute,
  NosotrosRoute: NosotrosRoute,
  ProcesoRoute: ProcesoRoute,
  ServiciosRoute: ServiciosRoute,
  MaterialesSlugRoute: MaterialesSlugRoute,
  MaterialesIndexRoute: MaterialesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
